### PR TITLE
Support utf8 display

### PR DESCRIPTION
**Pull request by lzhu666**
Support utf8 display

[before]：
TestForSyncProduct::test_1_valueValid[test Case Name-add]  
TestForSyncProduct::test_2_valueValid[\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0-update]

[now]：
TestForSyncProduct::test_1_valueValid[test Case Name-add]
TestForSyncProduct::test_2_valueValid[测试用例名称-update]

### CODE REVIEW

**Comment by BeyondEvil** [comment]
Ping @lzhu666 

I'd love to make a release ASAP and I would like for this to be included. But I want a test for it please. 🙏

**Comment by lzhu666** [comment]
> Ping @lzhu666
> 
> I'd love to make a release ASAP and I would like for this to be included. But I want a test for it please. 🙏

[utf8Display.zip](https://github.com/pytest-dev/pytest-html/files/3806867/utf8Display.zip)
please execute : pytest test_utf8Display.py --html=./report/report.html
Thanks!

**Comment by BeyondEvil** [comment]
> > Ping @lzhu666
> > I'd love to make a release ASAP and I would like for this to be included. But I want a test for it please. 🙏
> 
> [utf8Display.zip](https://github.com/pytest-dev/pytest-html/files/3806867/utf8Display.zip)
> please execute : pytest test_utf8Display.py --html=./report/report.html
> Thanks!

@lzhu666 Thanks, but what I meant was to add a test to the project. 😊 

Also, this is out of sync with master and so needs an update.

Thanks! 🙏

**Comment by lzhu666** [comment]
> > > Ping @lzhu666
> > > I'd love to make a release ASAP and I would like for this to be included. But I want a test for it please. 🙏
> > 
> > 
> > [utf8Display.zip](https://github.com/pytest-dev/pytest-html/files/3806867/utf8Display.zip)
> > please execute : pytest test_utf8Display.py --html=./report/report.html
> > Thanks!
> 
> @lzhu666 Thanks, but what I meant was to add a test to the project. 😊
> 
> Also, this is out of sync with master and so needs an update.
> 
> Thanks! 🙏

I've added test, and already in sync with master.
Thanks!

**Pull request merged**
