### PR TITLE
Use pre-commit to streamline development

### PR DESCRIPTION
**Pull request by BeyondEvil**
Let's use `pre-commit` for this project too.

### CODE REVIEW

**Comment by BeyondEvil** [comment]
Did someone add Bruno Rocha yet? @davehunt

**Comment by davehunt** [comment]
> Did someone add Bruno Rocha yet? @davehunt

Not yet. @rochacbruno would you like to review this patch for @BeyondEvil?

**Comment by davehunt** [comment]
I've invited @rochacbruno to collaborate on the repo. If this goes well we can add them as a developer with write access.

**Comment by rochacbruno** [comment]
Hi @davehunt accepted your invite! thanks.

I'll do a review of this PR later today :)

**Comment by BeyondEvil** [comment]
Welcome @rochacbruno ! 🙏

**Comment by BeyondEvil** [comment]
Thanks @rochacbruno !

Nice, feel free to add or recommend any additions you think might be good! :)

**Pull request merged**
