### PR TITLE
move module to src directory

### PR DESCRIPTION
**Pull request by jkowalleck**
moved sources to folder `src`.
as stated here: https://github.com/pytest-dev/pytest-html/pull/383#issuecomment-734821707

### CODE REVIEW

**Review by ssbarnea — APPROVED** [review]

**Comment by gnikonorov** [comment]
Why did we need to move things into a src directory again? I think we should update the PR description so people know why this change happened @jkowalleck @ssbarnea. 

Also why do we have a 'pytest-html' folder inside 'src'? why can't we remove the 'pytest-html' folder?

**Comment by ssbarnea** [comment]
@gnikonorov I do not have time to explain it now (or to find the backing blog posts), but have a look at https://github.com/pytest-dev/pytest/tree/master/src -- Is not that I would find everything that pytest did as ideal, but the repository layout was one of the good ones for sure.

Think as src as the place where modules should stay, most of the time is a single module. It is future proof and also integrates very well with other tools/IDEs.

**Comment by jkowalleck** [comment]
@gnikonorov updated the PRs description in a way the decision gets more context.
do you have suggestions how to improve the decision docs?

**Comment by gnikonorov** [comment]
> @gnikonorov I do not have time to explain it now (or to find the backing blog posts), but have a look at https://github.com/pytest-dev/pytest/tree/master/src -- Is not that I would find everything that pytest did as ideal, but the repository layout was one of the good ones for sure.
> 
> Think as src as the place where modules should stay, most of the time is a single module. It is future proof and also integrates very well with other tools/IDEs.

Thank you for clarifying, @ssbarnea 

> @gnikonorov updated the PRs description in a way the decision gets more context.
> do you have suggestions how to improve the decision docs?

I think that's perfect, thank you for taking the time to write it!

**Pull request merged**
