### PR TITLE
Respect --show-capture=no flag

### PR DESCRIPTION
**Pull request by gnikonorov**
Make `pytest-html` respect the `--show-capture=no` pytest flag. Closes https://github.com/pytest-dev/pytest-html/issues/171

### CODE REVIEW

**Comment by BeyondEvil** [comment]
LGTM! Rebase and we should be good to go! @gnikonorov

**Comment by gnikonorov** [comment]
Thank you @BeyondEvil! I updated the release date for the next release as well.

As soon as https://github.com/pytest-dev/pytest-html/pull/360 merges we should release `3.0.0` and use it as a test for the new workflow

**Comment by gnikonorov** [comment]
Bump for a review / merge @BeyondEvil

**Review by ssbarnea — APPROVED** [review]

**Comment by jigree** [comment]
Is this version of pytest-html released.
I learned from this thread that --show-capture=no flag is fixed in it and I would love to use this option to get rid of log from my pytest html report. 
I tried upgrading pytest-html using ```pip install -U pytest-html``` but looks like 2.1.1.1 is still the latest version.

Really appreciate your response on above. Thank you !

**Comment by BeyondEvil** [comment]
@jigree We're planning a release this weekend. This should be included in that.

Thank you for your patience!

**Pull request merged**
