### PR TITLE
Support tox isolated builds

### PR DESCRIPTION
**Pull request by gnikonorov**
Support [isolated builds](https://tox.readthedocs.io/en/latest/config.html#conf-isolated_build) in `tox`, for a better developer experience

### CODE REVIEW

**Review by ssbarnea — APPROVED** [review]

**Comment by BeyondEvil** [comment]
What does this do and in what way does it lead to a better user experience @gnikonorov? 

Just trying to learn and understand. :) Read the tox docs, but that didn't give me a lot.

**Comment by gnikonorov** [comment]
@BeyondEvil, it creates a separate isolated environment for your tox run. That way it's guaranteed that your local environment doesn't interfere in any way with the tox run.

**Comment by BeyondEvil** [comment]
> @BeyondEvil, it creates a separate isolated environment for your tox run. That way it's guaranteed that your local environment doesn't interfere in any way with the tox run.

Ah, got it! Thanks! 👊

**Comment by ssbarnea** [comment]
There is a cost involved as this makes tox slower but yep, improved isolation also good, that is why I approved it.

**Pull request merged**
