### PR TITLE
adding English locale before datetime.now

### PR DESCRIPTION
**Pull request by avnaf**
previous pull request was setting locale too early and that change was overridden.

### CODE REVIEW

**Comment by RibeiroAna** [comment]
Hi, just a small advice: You don't need to re-open your pull request, you just need to make a new commit to the same branch. I'll take a look on your pull request.

**Comment by RibeiroAna** [comment]
Thank you for your PR. Could you add a test case on the file `/testing/test_pytest_html.py` showing us what kind of problem this PR solves? What I understood is that it allows unicode characters on test files, could you please create a test case with unicode characters?

**Comment by BeyondEvil** [comment]
@avnaf Any progress on this? Please let us know if you need some assistance! :)

**Comment by avnaf** [comment]
I have stopped working on it. It is a very small issue and was solved
locally

**Comment by BeyondEvil** [comment]
@RibeiroAna Since you were the lead on this, I'll leave the decision to you whether to close it or not. :)

**Pull request closed without merging**
