### PR TITLE
Title of checkbox disappears when unchecked

### LINKED ISSUE #90: Title of checkbox disappears when unchecked
image

image

Regression was introduced in 972058bb. Reverting changes for main.js returned previous behaviour.

### PR DESCRIPTION
**Pull request by vashirov**
Fixes #90

### CODE REVIEW

**Comment by davehunt** [comment]
Closing/reopening to see if that triggers running the JavaScript tests in CircleCI.

**Comment by davehunt** [comment]
@vashirov these changes have the potential to cause failures in the JavaScript tests, but for some reason I couldn't get CircleCI to build and run these. I've moved the execution of these tests into Travis CI, so could you pull in the upstream changes and update your remote branch? Once we have a green Travis CI run with the JavaScript tests, I'd be confident enough to merge. Thanks!

**Comment by vashirov** [comment]
@davehunt done!

**Comment by davehunt** [comment]
Thanks @vashirov I'll tag a new release this morning.

**Pull request merged**
