### PR TITLE
Enable eslint camelcase rule

### PR DESCRIPTION
**Pull request by gnikonorov**
This PR enables [camelcase](https://eslint.org/docs/rules/camelcase) in eslint. I think this makes sense as most of the JavaScript in this repo is already camelcased, and it makes sense to have all variables follow the same convention.

I tested the changes locally and couldn't find any issues with this PR.

### CODE REVIEW

**Review by BeyondEvil — APPROVED** [review]
LGTM 👍

**Comment by gnikonorov** [comment]
Thanks @BeyondEvil ! If you're OK with it can you merge this PR?

**Comment by BeyondEvil** [comment]
Rerun test failed for Win`doh`es  

I hate windows, so for me, I'm fine with adding [pytest-rerunfailures](https://pypi.org/project/pytest-rerunfailures/) and marking that test, ironically, to rerun. @gnikonorov @ssbarnea

**Comment by gnikonorov** [comment]
Sure, that works for me. Let me make a comment on the main discussion so we're not fragmented

**Pull request merged**
