### PR TITLE
Keep sort preference for previously sorted columns

### PR DESCRIPTION
**Pull request by wanam**
This fixes https://github.com/pytest-dev/pytest-html/issues/219

### CODE REVIEW

**Comment by BeyondEvil** [comment]
Thanks @wanam 

Could you add a test for this as well?

**Comment by wanam** [comment]
I added 2 assertions to check this issue on `sort_column` test.

**Comment by BeyondEvil** [comment]
Could you update with master and fix failing tests @wanam ?

**Comment by wanam** [comment]
@BeyondEvil I'm getting some troubles trying to install your CI environment because of a grunt-contrib-qunit's dependency 'puppeteer' that fails to download Chromium module, maybe because I'm behind a proxy...

Anyway executing the tests on Chrome browser gave me the same result with the 3 failed tests, this cannot reproduced on my default browser: Firefox, do you have any idea what could be the reason for this?

**Comment by BeyondEvil** [comment]
js tests and related issues are not my fortay. Maybe @RibeiroAna has some input? 

If not, I'll see if I can illicit some help from a colleague. 🤷‍♂

**Comment by wanam** [comment]
I still don't understand why we have different behavior on Firefox vs Chrome, but I just pushed a fix for the sorting issue, the root cause was in case of equal keys, for this case the sort function should return 0.

@BeyondEvil If it's ok to merge, could you squash my commits into one commit?

**Pull request merged**
