### PR TITLE
Remove usage of funcargs

### LINKED ISSUE #282: 2.1.0 release causing object has no attribute 'funcargs'
Apparently the release of `pytest-html==2.1.0` broke our CI https://logserver.rdoproject.org/74/24774/67/check/rdo-tox-molecule/db3175d/job-output.txt

For the time being, I will pin-down: `pytest-html<2.1.0`

This bug is likely to affect any user of molecule, as we recommended using pytest-html to improve the reporting, but it is not a direct dependency of molecule tool itself, so we cannot really change module to workaround it.

### PR DESCRIPTION
**Pull request by christiansandberg**
Fixes #282

### CODE REVIEW

**Comment by ssbarnea** [comment]
I can confirm that this patch work fine. Can we please merge it and have a dot release?

**Comment by ssbarnea** [comment]
@BeyondEvil @davehunt please review.

**Comment by BeyondEvil** [comment]
I'll try to get around to releasing this today. Whole family is sick, so I'm pretty low on energy unfortunately.

I appreciate everyones' input!

**Comment by BeyondEvil** [comment]
In an effort to avoid globals (I have a personal crusade against them), here's my suggestion:

```python
@pytest.fixture
def extra(pytestconfig):
    """Add details to the HTML reports.

    .. code-block:: python

        import pytest_html
        def test_foo(extra):
            extra.append(pytest_html.extras.url('http://www.example.com/'))
    """
    pytestconfig.extras = []
    return pytestconfig.extras
```

which would turn

`fixture_extras = item.funcargs.get("extra", [])`

into

`fixture_extras = getattr(item.config, "extras", [])`

Thoughts @christiansandberg @ssbarnea @nicoddemus @RonnyPfannschmidt ?

**Comment by BeyondEvil** [comment]
Found a bug (present in all solutions). The extra is not emptied between tests, so if test A sets an extra and is run before test B that doesn't, test B still gets the extra. Will work on a fix.

**Comment by christiansandberg** [comment]
I’m also home with the kids, trying to get some work done. 🙄

Attaching it to the config is fine, although that’s also pretty much global.

Maybe you can empty the list on teardown instead?

**Comment by BeyondEvil** [comment]
> I’m also home with the kids, trying to get some work done. 🙄

I feel you! ❤️ 

> Attaching it to the config is fine, although that’s also pretty much global.

Yes, but in a much more controlled way 😊 

> Maybe you can empty the list on teardown instead?

See my updated solution 😉 

@christiansandberg

**Comment by BeyondEvil** [comment]
Looks like these tests are failing on master as well. Not sure why or how.

Please confirm. If true, I'll see if I can fix it.

**Comment by BeyondEvil** [comment]
The lastest build to pass was the release of [v2.1.0](https://travis-ci.org/github/pytest-dev/pytest-html/builds/661059875?utm_medium=notification&utm_source=github_status)

And I don't see that anything has been merged since. 🤔

**Comment by BeyondEvil** [comment]
It's the warning causing the failure:

```
testing/test_pytest_html.py::TestHTML::test_css_invalid_no_html
  /Users/jimbrannlund/dev/pytest-dev/pytest-html/.tox/py37/lib/python3.7/site-packages/_pytest/terminal.py:289: PytestDeprecationWarning: TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw instead at your own risk.
  See https://docs.pytest.org/en/latest/deprecations.html#terminalreporter-writer for more information.
    "TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw instead at your own risk.\n"

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

Something must've changed in the latest release of pytest.

**Comment by BeyondEvil** [comment]
Seems to be an issue with the pytest plugin test utility `pytester`.

I've logged an issue: https://github.com/pytest-dev/pytest/issues/6936

**Comment by BeyondEvil** [comment]
Here's a temporary fix until they root cause is fixed:

```
diff --git a/testing/test_pytest_html.py b/testing/test_pytest_html.py
index 0b19c12..dcc6b18 100644
--- a/testing/test_pytest_html.py
+++ b/testing/test_pytest_html.py
@@ -14,7 +14,20 @@ import pytest
 pytest_plugins = ("pytester",)
 
 
+def handle_tr_writer_deprecation():
+    # Remove this function when they've fixed
+    # https://github.com/pytest-dev/pytest/issues/6936
+    import warnings
+    from _pytest.warnings import _setoption
+
+    arg = "ignore:TerminalReporter.writer:pytest.PytestDeprecationWarning"
+    _setoption(warnings, arg)
+
+
 def run(testdir, path="report.html", *args):
+    # TODO: Temporary hack until they fix
+    # https://github.com/pytest-dev/pytest/issues/6936
+    handle_tr_writer_deprecation()  # TODO: Temporary hack
     path = testdir.tmpdir.join(path)
     result = testdir.runpytest("--html", path, *args)
     return result, read_html(path)
@@ -878,6 +891,9 @@ class TestHTML:
         assert "No such file or directory: 'style.css'" in result.stderr.str()
 
     def test_css_invalid_no_html(self, testdir):
+        # TODO: Temporary hack until they fix
+        # https://github.com/pytest-dev/pytest/issues/6936
+        handle_tr_writer_deprecation()
         testdir.makepyfile("def test_pass(): pass")
         result = testdir.runpytest("--css", "style.css")
         assert result.ret == 0
```

So that we can get this merged and I can make a hotfix. @ssbarnea @christiansandberg

**Comment by christiansandberg** [comment]
Sorry for messing up. 🙏

**Comment by BeyondEvil** [comment]
> Sorry for messing up. 🙏

No worries! You fixed it, right? 😉

**Pull request merged**
