### PR TITLE
Remove pkg_resources

### LINKED ISSUE #275: Use importlib.resources rather than setuptools.pkg_resources
Could we change this package to use https://docs.python.org/3/library/importlib.html#importlib.resources.read_text? instead of pkg_resources from setuptools?

I see the following advantages

1) pip installing setuptools doesn't play nice with tools like https://github.com/jazzband/pip-tools
2) pkg_resources doesn't work with pyoxidizer https://pyoxidizer.readthedocs.io/en/stable/, 
3) importlib is part of the std library, meaning we have one less dependency (we can't always assume setuptools is going to be available, especially with things like pyinstaller, pyoxidize, etc)

The readme says we need python3.6 or newer, so we should be fine for compatibility, as importlib was added in 3.1. 

I'll put up a PR shortly, its a pretty minimal change

### PR DESCRIPTION
**Pull request by jkowalleck**
removed the use of `pkg_resources` as requested by #275. 
related: #276

### CODE REVIEW

**Review by ssbarnea — APPROVED** [review]

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Apparently you failed to obliterate it:
```
$ rg pkg_resources                                                                                                              testing/test_pytest_html.py:11:8:import pkg_resources
testing/test_pytest_html.py:339:19:        content = pkg_resources.resource_string(
testing/test_pytest_html.py:351:19:        content = pkg_resources.resource_string(
```

How about getting rid of it completly?

**Comment by jkowalleck** [comment]
@ssbarnea  regarding https://github.com/pytest-dev/pytest-html/pull/396#pullrequestreview-544003675

did leave it in for the following reasons:
* i wanted to show that these tests still pass.
* since its only tests that still use `pkg_resources` , it should not affect libraries that depend on `pytest_html` - since they don't use the test depencencies. or do they? or did i get the topic of #275. wrong?

**Comment by jmrgibson** [comment]
Yeah, this looks like it solves most of the problem. It doesn't help with pyoxidize though, given `__file__` isn't specified when you aren't running from source

**Comment by ssbarnea** [comment]
With the risk of upsetting @jmrgibson I am inclined to say "not my problem". AFAIK, __file__ being missing is not our issue, what the magic-application-bundlers are doing is fishy at best and likely breaks other tools too. I know that running code with eval would endup without a file but that is a python package/libary/module, it is not expected to not reside in a file.

If someone has a better approach, I would accept a patch addressing it,  am quite curious as shipping data files with python packages is not really uncommon and the only way I seen to load them was via __file__.

**Comment by jmrgibson** [comment]
To be clear, I'm in support of this PR, it still makes my life a little
easier :) the distribution independent way for loading files is using
importlib.resources, but since that is only available in 3.7,  we'll have
to wait until support is dropped for 3.6 to use that (or maybe use one of
the backported packages)

**Review by ssbarnea — APPROVED** [review]

**Comment by jkowalleck** [comment]
@jmrgibson 
queation is: does this PR really fix #275 and close #276?
or are these still open after the PR? if so, i need to edit my comments mentioning these, so they are not auto-closed.

**Comment by ssbarnea** [comment]
I am not sure if it covers all areas but I find its current form acceptable. We can look to address other bits in follow-ups, as I do not see a particular regression being introduced by it, only some other things to improve maybe.

**Comment by jkowalleck** [comment]
> I am not sure if it covers all areas but I find its current form acceptable. We can look to address other bits in follow-ups, as I do not see a particular regression being introduced by it, only some other things to improve maybe.

modified the PR message so it refers the other issues/PRs but does NOT close them.

**Pull request merged**
