### PR TITLE
Added support for ordering metadata dictionaries by key.

### LINKED ISSUE #245: Dictionaries in environment table a not sorted
As in Python dictionaries are not (usually) sorted printing the environment gives random results, making much harder to read it and to compare it with previous runs.

Example: http://logs.rdoproject.org/52/23152/1/check/rdo-tox-molecule/6eb5f91/tox/reports.html

### PR DESCRIPTION
**Pull request by ExaltedBagel**
# Summary
This pull request fixes #245 by sorting environment metadata dictionaries by keys.

## Limitations

- This fix does not implement any form of recursion. This means that if you have a metadata value which has a dictionnary value, this inner dictionary will not be sorted.
- In order to be able to compare the dictionary key values, they are cast as string. This allows a lexical sorting order, which is a natural way of sorting.

### CODE REVIEW

**Comment by ExaltedBagel** [comment]
Seems ready to go. Tell me if you would like a greater test coverage.

**Comment by BeyondEvil** [comment]
Nice! Looks really good, thanks for this!

Greater test coverage would be greatly appreciated. For instance, will it handle metadata that is script/html?

As for the limitations, I think those are totally fine. Easy enough to extend your work if the need should arise.

Please rebase with master (I merged your other PR 🙏 ).

**Comment by ExaltedBagel** [comment]
The test for the dictionary containing some html has been done. It seems to be behaving as expected. I cleaned up the code a bit too. If your review is positive, I would be ready to merge!

**Comment by BeyondEvil** [comment]
**Released in v2.1.0**

**Pull request merged**
