### PR TITLE
Allow for redacting of environment table values

### PR DESCRIPTION
**Pull request by gnikonorov**
This PR enables the redaction of environment table values based on the newly added `environment_table_redact_list` INI key.

Please see the following for an example of a redacted environment table entry (`MY_SECRET_KEY`):
Screen Shot 2020-12-19 at 10 26 04 AM

Closes https://github.com/pytest-dev/pytest-html/issues/233

### CODE REVIEW

**Comment by gnikonorov** [comment]
Bump for a review @BeyondEvil / @ssbarnea

**Comment by gnikonorov** [comment]
Bump for a review, @BeyondEvil

**Comment by BeyondEvil** [comment]
Hey @gnikonorov !

Sorry for the delay! First the holidays and now I'm moving houses so my activity here is not going to be super high unfortunately.

**Review by BeyondEvil — APPROVED** [review]
Great work! 🙏

**Comment by gnikonorov** [comment]
Thanks for the review @BeyondEvil!

No worries at all! Happy new year and hope the move goes smoothly.

**Pull request merged**
