### PR TITLE
Add dependabot config

### PR DESCRIPTION
**Pull request by BeyondEvil**

### CODE REVIEW

**Comment by gnikonorov** [comment]
Do we need to wait on an answer for https://github.com/dependabot/dependabot-core/issues/2040 before we can merge this?

It sounds like https://github.com/dependabot/dependabot-core/issues/1524 is not a concern, right?

**Comment by BeyondEvil** [comment]
> Do we need to wait on an answer for [dependabot/dependabot-core#2040](https://github.com/dependabot/dependabot-core/issues/2040) before we can merge this?

Well, we have `additional_dependencies` in our pre-commit config... so 🤷‍♂️ 

> It sounds like [dependabot/dependabot-core#1524](https://github.com/dependabot/dependabot-core/issues/1524) is not a concern, right?

Umm... that's the main functionality of keeping pre-commit config up-to-date by using dependabot, so not sure what you mean? 😊

**Comment by gnikonorov** [comment]
> > It sounds like [dependabot/dependabot-core#1524](https://github.com/dependabot/dependabot-core/issues/1524) is not a concern, right?
> 
> Umm... that's the main functionality of keeping pre-commit config up-to-date by using dependabot, so not sure what you mean? 😊

I'm referencing https://github.com/dependabot/dependabot-core/issues/1524#issuecomment-744007983

**Comment by BeyondEvil** [comment]
> > > It sounds like [dependabot/dependabot-core#1524](https://github.com/dependabot/dependabot-core/issues/1524) is not a concern, right?
> > 
> > 
> > Umm... that's the main functionality of keeping pre-commit config up-to-date by using dependabot, so not sure what you mean? 😊
> 
> I'm referencing [dependabot/dependabot-core#1524 (comment)](https://github.com/dependabot/dependabot-core/issues/1524#issuecomment-744007983)

Ah!

Well, I turned it on for the repo. But I'm going to turn it off again. After some thought I don't want to maintain two different solutions that are tightly coupled. Since we likely won't bump these dev-dependencies very often, I'm just going to add comments to both places to remember.

**Pull request closed without merging**
