### PR TITLE
Rename master branch to main

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Comment by BeyondEvil** [comment]
I've reverted this PR.

You *do not* merge a PR this disruptive without approval.

We can make this change once v4 (next-gen) has been released.

**Comment by ssbarnea** [comment]
@BeyondEvil I would like to challenge you to explain what is disruptive about branch renaming? Over the last 2+ years, I did this on over a hundred of repos, and I am yet to see the what becomes disruptive.

**Comment by BeyondEvil** [comment]
Every ref, fork and alias needs updating.

**Comment by ssbarnea** [comment]
Apparently you are not aware about the fact that github redirects old name to new one, so you can still clone and pull from outdated urls. They did it quite well. Even the PR are kept open.

TBH; that is the first time when I see someone opposing that move. In fact before doing the rename I asked Ronny on irc about a possible wide move for the entire @pytest-dev so we could have consistent branch naming. Obviously that the wide move would need to be announced.

**Comment by BeyondEvil** [comment]
Will GH fix my aliases too?

**Comment by RonnyPfannschmidt** [comment]
ideally i want an eventual switch of all of pytest-dev to the "new" branch names,
however its important that its as painless as possible for the active maintainers of each repository

im fairly low on band-with for this myself for quite a while longer

i believe for pytest-html the most painless switchover will when v4 lands

**Pull request merged**
