### PR TITLE
Customize collapsed rows with a query param

### LINKED ISSUE #157: feature request - open html log with closed details
Hi there,
We have adopted pytest-html to view our tests.
However, when a test fails it open the html file in a way we can't read it (it prints out the entire stacktrace + logs we are writing during the test).

It would be appropriate if we can pass down a value to close the html details of a failed/errored test and not opening it by default.

Thanks,
Mor

### PR DESCRIPTION
**Pull request by jacebrowning**
Closes #157 

The query param code is based on https://stackoverflow.com/a/5158301/429533.

### CODE REVIEW

**Comment by jacebrowning** [comment]
> Expected: undefined, Actual: null

@davehunt Could you help me reason about these JavaScript failures?

**Comment by davehunt** [comment]
Took me a while, but it appears that PhantomJS doesn't support `String.includes`... here's a solution from StackOverflow: https://stackoverflow.com/a/31361163/154975 I'd suggest adding this to `test.js`.

**Comment by jacebrowning** [comment]
@davehunt Thanks! This should be ready for review.

**Comment by davehunt** [comment]
Thanks @jacebrowning!

**Comment by Formartha** [comment]
Great!!

**Pull request merged**
