### PR TITLE
Table Configuration

### PR DESCRIPTION
**Pull request by michael-hart**
I've written a basic implementation to #40. It has documentation and passes the same tests as before. However, it lacks assertions and tests to cover the new functionality.

### CODE REVIEW

**Comment by michael-hart** [comment]
Hi, the tests are failing at present, but they can be fixed - I'd just like some confirmation that this is a desirable feature before I spend time writing further tests. Is this PR something you are interested in?

**Comment by davehunt** [comment]
Sorry for the silence.. I do like the idea of columns being configurable by the user, but I haven't spent a lot of time thinking about it. This summer I'll be mentoring @RibeiroAna on several enhancements to this plugin, so I may ask her to look through your patch and help us to move it forward.

**Comment by RibeiroAna** [comment]
Hi @davehunt, I'll take a look =)

**Comment by davehunt** [comment]
@michael-hart are you still interested in working on this? Looking over your patch, I think a better approach would be to implement custom hooks for the table headers and columns. We could build the row as a list of cells, as you have in `_appendrow` and then call a hook such as `pytest_html_results_table_row(cells)`. We can then do the same for the header with a `pytest_html_results_table_header(cells)`. This would allow a user to implement these hooks and modify/add to the list of cells.

**Comment by michael-hart** [comment]
Hi, I'm a bit busy at the moment, but I can probably take a look in a few weeks?

**Comment by davehunt** [comment]
@michael-hart I decided to give it a go myself, and have a solution in #104. If you have time, please take a look and leave feedback. Closing this pull request in favour of the new approach.

**Pull request closed without merging**
