### PR TITLE
Allow for report duration formatting

### PR DESCRIPTION
**Pull request by gnikonorov**
Allow for formatting the `Duration` column on the report. The supported format specifiers are those defined for [time.strftime](https://docs.python.org/3/library/time.html#time.strftime) plus `%f` ( for milliseconds ).

Closes https://github.com/pytest-dev/pytest-html/issues/376

### CODE REVIEW

**Comment by ssbarnea** [comment]
@gnikonorov Please disable the codecov comment, is noise/spam. We have an action check for it, if it fails we will be able to read it.

**Comment by ssbarnea** [comment]
Are you sure we do not loose the sorting ability with it?

**Review by BeyondEvil — APPROVED** [review]
Nice! 👍

**Comment by gnikonorov** [comment]
> @gnikonorov Please disable the codecov comment, is noise/spam. We have an action check for it, if it fails we will be able to read it.

Sure. I'll disable it when I'm at my computer later today.

**Comment by gnikonorov** [comment]
> Are you sure we do not loose the sorting ability with it?

@ssbarnea I tested sorting the column with a few different 'duration_formatter' strings and with the default format and it worked

**Review by ssbarnea — APPROVED** [review]
I tested it locally and it seams ok.

**Pull request merged**
