### PR TITLE
use importlib.resources instead of setuptools for loading css and js 

### PR DESCRIPTION
**Pull request by jmrgibson**
Fixes: #275

### CODE REVIEW

**Comment by BeyondEvil** [comment]
Hi! Mind describing why this is good?

Also, tests are failing. :)

**Comment by jmrgibson** [comment]
Sorry, I'm not super familiar with the GH interface. The issue is here: https://github.com/pytest-dev/pytest-html/pull/276#issue-383050601
It doesn't look like I have permission to add linked issues to this PR?

Looking at the tests now...

**Comment by BeyondEvil** [comment]
No worries, I edited the main description/comment with a common way of linking.

Basically what you did in the comment above. :) @jmrgibson

**Comment by BeyondEvil** [comment]
Here's a good read that might help you: https://github.com/pytest-dev/pytest-html/blob/master/development.rst

**Comment by jmrgibson** [comment]
Bah, `importlib` was added in 3.1, but `importlib.resources` is only available in 3.7. I could make the selection of `pkg_resources` vs `importlib.resources` determined at runtime based on the version, can take a look at the rational in the linked issue, and let me know if you think it's worth adding? Otherwise I'll just maintain my own fork (I'm running 3.7 in pyoxidize).

**Comment by BeyondEvil** [comment]
Ok, I'll dive a little deeper into this in the coming days. Ping me next week if you haven't heard anything. 👍

**Comment by jmrgibson** [comment]
Pinging @BeyondEvil  :) Hope you aren't too affected by COVID-19, did you get a chance to look at importlib.resources?

**Comment by BeyondEvil** [comment]
Actually, the whole family has been sick. Still are even. Not Covid19 tho. I think, haha.

So haven't had a chance yet, but will get to it.

**Comment by jkowalleck** [comment]
created an alternative solution via PR #396

**Comment by BeyondEvil** [comment]
Should we close this in favor of #396 ? 

@jmrgibson @ssbarnea @gnikonorov

**Comment by jmrgibson** [comment]
Yeah, fine to close it, someone can re-open it again if/when it is decided that we're going drop 3.6 support

**Pull request closed without merging**
