### PR TITLE
Move documentation to read the docs

### PR DESCRIPTION
**Pull request by gnikonorov**
This PR moves our documentation from rst files in the project root to read the docs.

The docs are located at https://pytest-html.readthedocs.io/en/latest/. Note that nothing is found yet since docs build upon merge to master, and we have not yet built any docs. I built them locally and things looked fine.

If you want to see the generated documentation as part of your review, you can check out this branch and run `tox -e docs`. Then run a webserver from `docs/_build/html`.

I intentionally kept the documentation as similar to the current documentation as possible to reduce the scope of this PR.

**NOTE**: I'll remove the existing documentation once this merges and properly builds, since I don't want to delete the documentation until I'm confident this works as expected.

**NOTE**: This needs to take https://github.com/pytest-dev/pytest-html/pull/400 into account if it merges  before this PR is in

### CODE REVIEW

**Comment by gnikonorov** [comment]
Bump for a review/merge @BeyondEvil and/or @ssbarnea

**Comment by ssbarnea** [comment]
@gnikonorov Please add me (ssbarnea) on RTD, so I can configure the repo too. I want to enable RTD app too, as RTD can also build PRs and make them available so user can browse the docsite build with their own changes.

**Comment by gnikonorov** [comment]
> @gnikonorov Please add me (ssbarnea) on RTD, so I can configure the repo too. I want to enable RTD app too, as RTD can also build PRs and make them available so user can browse the docsite build with their own changes.

Of course @ssbarnea I'll add you tonight. @BeyondEvil are you on RTD?

**Comment by gnikonorov** [comment]
@ssbarnea I added you as a maintainer on readthedocs.

Note this PR is intentionally onlly setting up the documentation, since I wanted to keep scope as small as possible. I have some follow ups planned once this PR merges

**Review by BeyondEvil — COMMENTED** [review]
This is new territory as I've never set something like this up before!

If you don't mind, as a comment (preferably in the OP), could you describe for each file (related to RTD) explain what is going on?

If @ssbarnea has more experience with RTD I'd be great if he could review this.

**Comment by BeyondEvil** [comment]
>  @BeyondEvil are you on RTD?

I don't think so. I'll create an account.

**Comment by ssbarnea** [comment]
@gnikonorov As you can see I managed to enable RTD to build PRs. If it succeeds it should produce browsable site. We should also keep our own tox build of the docs as this assures that local building also works.

But from the review point of view of docs changes, we should look at the RTD job and evaluated if the change works or not as intended.

**Comment by gnikonorov** [comment]
@ssbarnea it looks good to me. 

Can we please merge this in sooner rather than later if we're happy? It's breaking open PRs since the project is trying to build docs that don't exist (https://github.com/pytest-dev/pytest-html/pull/393 for example)

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
