### PR TITLE
Add ANSI support in html report

### PR DESCRIPTION
**Pull request by premkarat**
Dave,
I missed to fetch changes from pytest-dev:master branch to my master branch, so had difficulties in doing a rebase. Finally I have cleaned up my repo and added required changes. Sorry for the confusion.

https://github.com/pytest-dev/pytest-html/pull/75

I have incorporated all the changes from the previous pull request above.

### CODE REVIEW

**Comment by premkarat** [comment]
@davehunt , Please let me know if any further work is required on this. TIA

**Comment by davehunt** [comment]
Merged in https://github.com/pytest-dev/pytest-html/commit/24e169d9a4b1ab0d4018442582a96af8034ea945 - thanks for the contribution @premkarat! 😄 I've tagged v1.11.0 so a new release should be out today.

**Comment by premkarat** [comment]
Super!. Thanks a bunch for helping me out.

**Comment by davehunt** [comment]
Hey @premkarat, due to ansi2html using the less permissive GPL license, the next version of pytest-html is likely to remove it as a dependency. See https://github.com/pytest-dev/pytest-html/issues/96 for more details. This just means you'll need to install it separately, so shouldn't be much of an inconvenience.

**Pull request closed without merging**
